/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as BusinessRouteRouteImport } from './routes/business/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffBookingsRouteImport } from './routes/staff/bookings'
import { Route as StaffPositionRouteImport } from './routes/staff/$position'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as BusinessUsersRouteImport } from './routes/business/users'
import { Route as BusinessTableRouteImport } from './routes/business/table'
import { Route as BusinessServiceRouteImport } from './routes/business/service'
import { Route as BusinessBookingRouteImport } from './routes/business/booking'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminServiceRouteImport } from './routes/admin/service'
import { Route as AdminBusinessRouteImport } from './routes/admin/business'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPositionRoute = StaffPositionRouteImport.update({
  id: '/$position',
  path: '/$position',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const BusinessUsersRoute = BusinessUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessTableRoute = BusinessTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessServiceRoute = BusinessServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessBookingRoute = BusinessBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServiceRoute = AdminServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessRoute = AdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/business': typeof AdminBusinessRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/booking': typeof BusinessBookingRoute
  '/business/service': typeof BusinessServiceRoute
  '/business/table': typeof BusinessTableRoute
  '/business/users': typeof BusinessUsersRoute
  '/client/profile': typeof ClientProfileRoute
  '/staff/$position': typeof StaffPositionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/business/': typeof BusinessIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/business': typeof AdminBusinessRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/booking': typeof BusinessBookingRoute
  '/business/service': typeof BusinessServiceRoute
  '/business/table': typeof BusinessTableRoute
  '/business/users': typeof BusinessUsersRoute
  '/client/profile': typeof ClientProfileRoute
  '/staff/$position': typeof StaffPositionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/business': typeof BusinessIndexRoute
  '/staff': typeof StaffIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/admin/business': typeof AdminBusinessRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/booking': typeof BusinessBookingRoute
  '/business/service': typeof BusinessServiceRoute
  '/business/table': typeof BusinessTableRoute
  '/business/users': typeof BusinessUsersRoute
  '/client/profile': typeof ClientProfileRoute
  '/staff/$position': typeof StaffPositionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/business/': typeof BusinessIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/business'
    | '/staff'
    | '/client'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/business'
    | '/admin/service'
    | '/admin/users'
    | '/business/booking'
    | '/business/service'
    | '/business/table'
    | '/business/users'
    | '/client/profile'
    | '/staff/$position'
    | '/staff/bookings'
    | '/staff/dashboard'
    | '/business/'
    | '/staff/'
    | '/errors/$error'
    | '/help-center'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/client'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/business'
    | '/admin/service'
    | '/admin/users'
    | '/business/booking'
    | '/business/service'
    | '/business/table'
    | '/business/users'
    | '/client/profile'
    | '/staff/$position'
    | '/staff/bookings'
    | '/staff/dashboard'
    | '/business'
    | '/staff'
    | '/errors/$error'
    | '/help-center'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/business'
    | '/staff'
    | '/client'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/admin/business'
    | '/admin/service'
    | '/admin/users'
    | '/business/booking'
    | '/business/service'
    | '/business/table'
    | '/business/users'
    | '/client/profile'
    | '/staff/$position'
    | '/staff/bookings'
    | '/staff/dashboard'
    | '/business/'
    | '/staff/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/help-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/$position': {
      id: '/staff/$position'
      path: '/$position'
      fullPath: '/staff/$position'
      preLoaderRoute: typeof StaffPositionRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/business/users': {
      id: '/business/users'
      path: '/users'
      fullPath: '/business/users'
      preLoaderRoute: typeof BusinessUsersRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/table': {
      id: '/business/table'
      path: '/table'
      fullPath: '/business/table'
      preLoaderRoute: typeof BusinessTableRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/service': {
      id: '/business/service'
      path: '/service'
      fullPath: '/business/service'
      preLoaderRoute: typeof BusinessServiceRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/booking': {
      id: '/business/booking'
      path: '/booking'
      fullPath: '/business/booking'
      preLoaderRoute: typeof BusinessBookingRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/service': {
      id: '/admin/service'
      path: '/service'
      fullPath: '/admin/service'
      preLoaderRoute: typeof AdminServiceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminBusinessRoute: typeof AdminBusinessRoute
  AdminServiceRoute: typeof AdminServiceRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBusinessRoute: AdminBusinessRoute,
  AdminServiceRoute: AdminServiceRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BusinessRouteRouteChildren {
  BusinessBookingRoute: typeof BusinessBookingRoute
  BusinessServiceRoute: typeof BusinessServiceRoute
  BusinessTableRoute: typeof BusinessTableRoute
  BusinessUsersRoute: typeof BusinessUsersRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessBookingRoute: BusinessBookingRoute,
  BusinessServiceRoute: BusinessServiceRoute,
  BusinessTableRoute: BusinessTableRoute,
  BusinessUsersRoute: BusinessUsersRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffPositionRoute: typeof StaffPositionRoute
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffPositionRoute: StaffPositionRoute,
  StaffBookingsRoute: StaffBookingsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface ClientRouteChildren {
  ClientProfileRoute: typeof ClientProfileRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientProfileRoute: ClientProfileRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
